name: ecf_dgii
description: Generador de Ecf y Aprobaciones Comerciales firmados que seran enviados a la DGII para su posterior validacion
version: 1.0.23
repository: https://github.com/Josue0z/ecf_dgii.git

environment:
  sdk: ^3.6.2
  flutter: '>=3.0.0'

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.1
  http: ^1.4.0
  path_provider: ^2.1.5
  xml: ^6.5.0
  crypto: ^3.0.6
  asn1lib: ^1.6.5
  pointycastle: ^4.0.0
  basic_utils: ^5.8.2
  http_parser: ^4.1.2
  intl: ^0.20.2
  xml_crypto: ^3.2.1+1
  pdf: ^3.11.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0


platforms:
  macos:
  windows: