
import 'package:ecf_dgii/settings.dart'; // aquí están las variables
import 'package:ecf_dgii/src/models/ecf.model.dart';
import 'package:ecf_dgii/src/types/ecf.dart';
   List<EcfDetailsModel> items = [
      EcfDetailsModel(
          cantidad: '1',
          unidadMedida: '23',
          codigos: [TipoCodigo(tipoCodigo: 'Interno', codigoItem: '1521')],
          indicadorFacturacion: '1',
          indicadorBienOServ: '1',
          nombreItem: 'Gouda Import',
          descripcionItem: '',
          precioUnitario: '179.0000',
          descuentoMonto: '',
          subDescuentos: [],
          recargoMonto: '',
          subRecargos: [],
          impuestosAdicionales: [],
          fechaElaboracion: '20-12-2019',
          fechaVencimientoItem: '10-10-2020',
          montoItem: '179.00'),
      EcfDetailsModel(
          cantidad: '2',
          unidadMedida: '23',
          codigos: [TipoCodigo(tipoCodigo: 'Interno', codigoItem: '1521')],
          indicadorFacturacion: '1',
          indicadorBienOServ: '1',
          nombreItem: 'Gouda Impor Lonja',
          descripcionItem: '',
          precioUnitario: '179.0000',
          descuentoMonto: '',
          subDescuentos: [],
          recargoMonto: '',
          subRecargos: [],
          impuestosAdicionales: [],
          fechaElaboracion: '30-12-2019',
          fechaVencimientoItem: '10-10-2020',
          montoItem: '358.00'),
      EcfDetailsModel(
          cantidad: '1',
          unidadMedida: '43',
          codigos: [TipoCodigo(tipoCodigo: 'Interno', codigoItem: '1521')],
          indicadorFacturacion: '1',
          indicadorBienOServ: '1',
          nombreItem: 'Bon Helado',
          descripcionItem: '',
          precioUnitario: '239.0000',
          descuentoMonto: '',
          subDescuentos: [],
          recargoMonto: '',
          subRecargos: [],
          impuestosAdicionales: [],
          fechaElaboracion: '30-12-2019',
          fechaVencimientoItem: '10-10-2020',
          montoItem: '239.00'),
      EcfDetailsModel(
          cantidad: '2',
          unidadMedida: '43',
          codigos: [TipoCodigo(tipoCodigo: 'Interno', codigoItem: '1521')],
          indicadorFacturacion: '2',
          indicadorBienOServ: '1',
          nombreItem: 'Butterball pavo',
          descripcionItem: '',
          precioUnitario: '155.0000',
          descuentoMonto: '',
          subDescuentos: [],
          recargoMonto: '',
          subRecargos: [],
          impuestosAdicionales: [],
          fechaElaboracion: '20-12-2019',
          fechaVencimientoItem: '10-10-2020',
          montoItem: '310.00'),
      EcfDetailsModel(
          cantidad: '1',
          unidadMedida: '43',
          codigos: [TipoCodigo(tipoCodigo: 'Interno', codigoItem: '1521')],
          indicadorFacturacion: '2',
          indicadorBienOServ: '1',
          nombreItem: 'Yogurt Natural S/A',
          descripcionItem: '',
          precioUnitario: '189.0000',
          descuentoMonto: '',
          subDescuentos: [],
          recargoMonto: '',
          subRecargos: [],
          impuestosAdicionales: [],
          fechaElaboracion: '10-04-2020',
          fechaVencimientoItem: '25-05-2020',
          montoItem: '189.00'),
      EcfDetailsModel(
          cantidad: '2',
          unidadMedida: '23',
          codigos: [TipoCodigo(tipoCodigo: 'Interno', codigoItem: '1521')],
          indicadorFacturacion: '4',
          indicadorBienOServ: '1',
          nombreItem: 'Albondigas de pollo',
          descripcionItem: '',
          precioUnitario: '115.0000',
          descuentoMonto: '',
          subDescuentos: [],
          recargoMonto: '',
          subRecargos: [],
          impuestosAdicionales: [],
          fechaElaboracion: '11-04-2020',
          fechaVencimientoItem: '30-04-2020',
          montoItem: '230.00'),
    ];

    EcfModel ecf = EcfModel(
      tipoEcf: EcfType.e31,
      tempDirName: kTempDirName,          // antes: 'arenal'
      numeroComprobante: 'E310000000008', // comprobante actual
      codigoModificacion: '',
      fechaEmision: '01-04-2020',
      fechaVencimiento: kfechaVencimiento, // antes: '31-12-2028'
      fechaEmisionNcfModificado: '',
      razonModificacion: '',
      tipoIngreso: '01',
      tipoPago: '1',
      formasDePagos: [FormaDePago('1', '1505.00')],
      sucursal: '',
      municipio: '010100',
      provincia: '010000',
      telefonoEmisor1: '809-472-7676',
      telefonoEmisor2: '809-491-1918',
      telefonoEmisor3: '',
      totalPaginas: '',
      rncEmisor: kRncEmisor,              // antes: '123006624'
      razonSocialEmisor: 'DOCUMENTOS ELECTRONICOS DE 02',
      nombreComercial: 'DOCUMENTOS ELECTRONICOS DE 02',
      direccionEmisor: 'AVE. ISABEL AGUIAR NO. 269, ZONA INDUSTRIAL DE HERRERA',
      correoEmisor: 'DOCUMENTOSELECTRONICOSDE0612345678969789+9000000000000000000000000000001@123.COM',
      website: 'www.facturaelectronica.com',
      actividadEconomica: '',
      codigoVendedor: 'AA0000000100000000010000000002000000000300000000050000000006',
      informacionAdicionalEmisor: '',
      rncComprador: '131880681',
      razonSocialComprador: 'DOCUMENTOS ELECTRONICOS DE 03',
      nombreComprador: '',
      contactoComprador: 'MARCOS LATIPLOL',
      correoComprador: 'MARCOSLATIPLOL@KKKK.COM',
      telefonoAdicional: '',
      direccionComprador: 'CALLE JACINTO DE LA CONCHA FELIZ ESQUINA 27 DE FEBRERO,FRENTE A DOMINO',
      municipioComprador: '010100',
      provinciaComprador: '010000',
      codigoInternoComprador: '10633440',
      fechaEntrega: '10-10-2020',
      fechaOrdenCompra: '10-11-2018',
      numeroOrdenCompra: '4500352238',
      numeroFacturaInterna: '123456789016',
      numeroPedidoInterno: '123456789016',
      numeroContenedor: '',
      numeroReferencia: '',
      zonaVenta: 'NORTE',
      rutaVenta: '',
      indicadorMontoGravado: '1',
      totalGravado: '1087.80',
      totalGravado18: '657.63',
      totalGravado16: '430.17',
      totalGravadoTasa0: '',
      montoExento: '230.00',
      totalItbis: '187.20',
      totalItbis18: '118.37',
      totalItbis16: '68.83',
      totalItbisTasa0: '',
      itbis1: '18',
      itbis2: '16',
      itbis3: '',
      montoPeriodo: '1505.00',
      montoAvancePago: '',
      valorPagar: '1505.00',
      totalItbisRetencion: '',
      totalIsrRetencion: '',
      montoImpuestoAdicional: '',
      impuestosAdicionales: [],
      montoTotal: '1505.00',
      terminoPago: '',
      bancoPago: '',
      paginas: [],
      items: items,
      privateKey: '',
      certBase64: ''
    );


EcfModel kE310000000008 = ecf;
