
import 'package:ecf_dgii/settings.dart';
import 'package:ecf_dgii/src/models/ecf.model.dart';
import 'package:ecf_dgii/src/types/ecf.dart';

    final fechaEmision = '01-04-2020';

    List<EcfDetailsModel> items = [
      EcfDetailsModel(
          cantidad: '50.00',
          unidadMedida: '5',
          codigos: [],
          indicadorFacturacion: '4',
          indicadorBienOServ: '1',
          nombreItem: 'Leche 12/24OZ',
          descripcionItem: '',
          precioUnitario: '350.0000',
          descuentoMonto: '100.00',
          subDescuentos: [
            SubDescuento(tipoSubDescuento: '\$', subDescuentoPorcentaje: '', montoSubDescuento: '100.00')
          ],
          impuestosAdicionales: [],
          otraMonedaDetalles: [],
          montoItem: '17400.00'),
      EcfDetailsModel(
          cantidad: '20.00',
          unidadMedida: '6',
          codigos: [],
          indicadorFacturacion: '4',
          indicadorBienOServ: '1',
          nombreItem: 'Huevo 18',
          descripcionItem: '',
          precioUnitario: '500.0000',
          descuentoMonto: '100.00',
          subDescuentos: [
            SubDescuento(tipoSubDescuento: '\$', subDescuentoPorcentaje: '', montoSubDescuento: '100.00')
          ],
          impuestosAdicionales: [],
          otraMonedaDetalles: [],
          montoItem: '9900.00'),
      EcfDetailsModel(
          cantidad: '30.00',
          unidadMedida: '31',
          codigos: [],
          indicadorFacturacion: '4',
          indicadorBienOServ: '1',
          nombreItem: 'Carnes paq 2lb',
          descripcionItem: '',
          precioUnitario: '475.0000',
          descuentoMonto: '100.00',
          subDescuentos: [
            SubDescuento(tipoSubDescuento: '\$', subDescuentoPorcentaje: '', montoSubDescuento: '100.00')
          ],
          impuestosAdicionales: [],
          otraMonedaDetalles: [],
          montoItem: '14150.00')
    ];

    EcfModel ecf = EcfModel(
        tipoEcf: EcfType.e31,
        tempDirName: kTempDirName,
        indicadorMontoGravado: '',
        indicadorNotaCredito: '',
        rncOtroContribuyente: '',
        numeroComprobante: 'E310000000009',
        numeroComprobanteModificado: '',
        codigoModificacion: '',
        fechaEmision: fechaEmision,
        fechaVencimiento: kfechaVencimiento,
        fechaEmisionNcfModificado: '',
        razonModificacion: '',
        tipoIngreso: '01',
        tipoPago: '1',
        formasDePagos: [],
        sucursal: '',
        municipio: '010100',
        provincia: '010000',
        telefonoEmisor1: '809-472-7676',
        telefonoEmisor2: '809-491-1918',
        telefonoEmisor3: '',
        totalPaginas: '',
        rncEmisor: kRncEmisor,
        razonSocialEmisor: 'DOCUMENTOS ELECTRONICOS DE 02',
        nombreComercial: 'DOCUMENTOS ELECTRONICOS DE 02',
        direccionEmisor:
            'AVE. ISABEL AGUIAR NO. 269, ZONA INDUSTRIAL DE HERRERA',
        correoEmisor:
            'DOCUMENTOSELECTRONICOSDE0612345678969789+9000000000000000000000000000001@123.COM',
        website: 'www.facturaelectronica.com',
        actividadEconomica: '',
        codigoVendedor:
            'AA0000000100000000010000000002000000000300000000050000000006',
        informacionAdicionalEmisor: '',
        rncComprador: '131880681',
        identificadorExtranjero: '',
        razonSocialComprador: 'DOCUMENTOS ELECTRONICOS DE 03',
        nombreComprador: '',
        contactoComprador: 'MARCOS LATIPLOL',
        correoComprador: 'MARCOSLATIPLOL@KKKK.COM',
        telefonoAdicional: '',
        direccionComprador:
            'CALLE JACINTO DE LA CONCHA FELIZ ESQUINA 27 DE FEBRERO,FRENTE A DOMINO',
        municipioComprador: '010100',
        provinciaComprador: '010000',
        codigoInternoComprador: '10633440',
        numeroContenedor: '',
        numeroReferencia: '',
        fechaEntrega: '10-10-2020',
        fechaOrdenCompra: '10-11-2018',
        numeroOrdenCompra: '4500352238',
        numeroFacturaInterna: '123456789016',
        numeroPedidoInterno: '123456789016',
        zonaVenta: 'NORTE',
        rutaVenta: '',
        paisDestino: '',
        conductor: '',
        documentoTransporte: '',
        ficha: '',
        placa: '',
        rutaTransporte: '',
        zonaTransporte: '',
        numeroAlbaran: '',
        totalGravado: '',
        totalGravado18: '',
        totalGravado16: '',
        totalGravadoTasa0: '',
        montoExento: '41450.00',
        totalItbis: '',
        totalItbis18: '',
        totalItbis16: '',
        totalItbisTasa0: '',
        itbis1: '',
        itbis2: '',
        itbis3: '',
        montoTotal: '41450.00',
        montoNoFacturable: '',
        montoPeriodo: '',
        montoAvancePago: '',
        valorPagar: '',
        tipoMoneda: '',
        tipoCambio: '',
        montoGravadoTotalOtraMoneda: '',
        montoGravadoTotalOtraMoneda1: '',
        montoGravadoTotalOtraMoneda2: '',
        montoGravadoTotalOtraMoneda3: '',
        totalItbisOtraMoneda: '',
        totalItbis1OtraMoneda: '',
        totalItbis2OtraMoneda: '',
        totalItbis3OtraMoneda: '',
        montoExentoOtraMoneda: '',
        montoTotalOtraMoneda: '',
        totalItbisRetencion: '',
        totalIsrRetencion: '',
        montoImpuestoAdicional: '',
        impuestosAdicionales: [],
        terminoPago: '',
        bancoPago: '',
        paginas: [],
        items: items,
        privateKey: '',
        certBase64: '');

   EcfModel kE310000000009 = ecf;
