
import 'package:ecf_dgii/settings.dart';
import 'package:ecf_dgii/src/models/ecf.model.dart';
import 'package:ecf_dgii/src/types/ecf.dart';

    List<EcfDetailsModel> items = [
      EcfDetailsModel(
          cantidad: '20.00',
          unidadMedida: '46',
          cantidadReferencia: '',
          unidadReferencia: '',
          indicadorFacturacion: '4',
          indicadorBienOServ: '1',
          nombreItem: 'ARROZ LA GARZA',
          descripcionItem: '',
          precioUnitarioReferencia: '',
          precioUnitario: '1500.0000',
          descuentoMonto: '',
          subCantidades: [],
          gradosAlcohol: '',
          subDescuentos: [],
          recargoMonto: '',
          subRecargos: [],
          impuestosAdicionales: [],
          montoItem: '30000.00'),
      EcfDetailsModel(
          cantidad: '40.00',
          unidadMedida: '46',
          cantidadReferencia: '',
          unidadReferencia: '',
          indicadorFacturacion: '2',
          indicadorBienOServ: '1',
          nombreItem: 'AZUCAR CREMA',
          descripcionItem: '',
          precioUnitarioReferencia: '',
          precioUnitario: '1300.0000',
          descuentoMonto: '',
          subCantidades: [],
          gradosAlcohol: '',
          subDescuentos: [],
          recargoMonto: '',
          subRecargos: [],
          impuestosAdicionales: [],
          montoItem: '52000.00'),
      EcfDetailsModel(
          cantidad: '50.00',
          unidadMedida: '14',
          cantidadReferencia: '',
          unidadReferencia: '',
          indicadorFacturacion: '1',
          indicadorBienOServ: '1',
          nombreItem: 'ESPAGUETIS MILANO',
          descripcionItem: '',
          precioUnitarioReferencia: '',
          precioUnitario: '900.0000',
          descuentoMonto: '',
          subCantidades: [],
          gradosAlcohol: '',
          subDescuentos: [],
          recargoMonto: '',
          subRecargos: [],
          impuestosAdicionales: [],
          montoItem: '45000.00'),
      EcfDetailsModel(
          cantidad: '25.00',
          unidadMedida: '47',
          cantidadReferencia: '',
          unidadReferencia: '',
          indicadorFacturacion: '4',
          indicadorBienOServ: '1',
          nombreItem: 'LECHE MILEX',
          descripcionItem: '',
          precioUnitarioReferencia: '',
          precioUnitario: '450.0000',
          descuentoMonto: '',
          subCantidades: [],
          gradosAlcohol: '',
          subDescuentos: [],
          recargoMonto: '',
          subRecargos: [],
          impuestosAdicionales: [],
          montoItem: '11250.00'),
      EcfDetailsModel(
          cantidad: '35.00',
          unidadMedida: '47',
          cantidadReferencia: '',
          unidadReferencia: '',
          indicadorFacturacion: '1',
          indicadorBienOServ: '1',
          nombreItem: 'SALSA LA FAMOSA',
          descripcionItem: '',
          precioUnitarioReferencia: '',
          precioUnitario: '200.0000',
          descuentoMonto: '',
          subCantidades: [],
          gradosAlcohol: '',
          subDescuentos: [],
          recargoMonto: '',
          subRecargos: [],
          impuestosAdicionales: [],
          montoItem: '7000.00'),
      EcfDetailsModel(
          cantidad: '55.00',
          unidadMedida: '14',
          cantidadReferencia: '',
          unidadReferencia: '',
          indicadorFacturacion: '1',
          indicadorBienOServ: '1',
          nombreItem: 'GALLETAS SALADAS GUARINA',
          descripcionItem: '',
          precioUnitarioReferencia: '',
          precioUnitario: '95.0000',
          descuentoMonto: '',
          subCantidades: [],
          gradosAlcohol: '',
          subDescuentos: [],
          recargoMonto: '',
          subRecargos: [],
          impuestosAdicionales: [],
          montoItem: '5225.00'),
      EcfDetailsModel(
          cantidad: '60.00',
          unidadMedida: '14',
          cantidadReferencia: '',
          unidadReferencia: '',
          indicadorFacturacion: '4',
          indicadorBienOServ: '1',
          nombreItem: 'SALAMI INDUVECA',
          descripcionItem: '',
          precioUnitarioReferencia: '',
          precioUnitario: '115.0000',
          descuentoMonto: '',
          subCantidades: [],
          gradosAlcohol: '',
          subDescuentos: [],
          recargoMonto: '',
          subRecargos: [],
          impuestosAdicionales: [],
          montoItem: '6900.00'),
      EcfDetailsModel(
          cantidad: '65.00',
          unidadMedida: '15',
          cantidadReferencia: '',
          unidadReferencia: '',
          indicadorFacturacion: '1',
          indicadorBienOServ: '1',
          nombreItem: 'JUGO DE NARANJA RICA',
          descripcionItem: '',
          precioUnitarioReferencia: '',
          precioUnitario: '100.0000',
          descuentoMonto: '',
          subCantidades: [],
          gradosAlcohol: '',
          subDescuentos: [],
          recargoMonto: '',
          subRecargos: [],
          impuestosAdicionales: [],
          montoItem: '6500.00'),
      EcfDetailsModel(
          cantidad: '25.00',
          unidadMedida: '47',
          cantidadReferencia: '',
          unidadReferencia: '',
          indicadorFacturacion: '1',
          indicadorBienOServ: '1',
          nombreItem: 'ACEITE CRISOL',
          descripcionItem: '',
          precioUnitarioReferencia: '',
          precioUnitario: '250.0000',
          descuentoMonto: '',
          subCantidades: [],
          gradosAlcohol: '',
          subDescuentos: [],
          recargoMonto: '',
          subRecargos: [],
          impuestosAdicionales: [],
          montoItem: '6250.00'),
      EcfDetailsModel(
          cantidad: '55.00',
          unidadMedida: '20',
          cantidadReferencia: '',
          unidadReferencia: '',
          indicadorFacturacion: '4',
          indicadorBienOServ: '1',
          nombreItem: 'HUEVOS CASCARON',
          descripcionItem: '',
          precioUnitarioReferencia: '',
          precioUnitario: '300.0000',
          descuentoMonto: '',
          subCantidades: [],
          gradosAlcohol: '',
          subDescuentos: [],
          recargoMonto: '',
          subRecargos: [],
          impuestosAdicionales: [],
          montoItem: '16500.00'),
      EcfDetailsModel(
          cantidad: '20.00',
          unidadMedida: '46',
          cantidadReferencia: '',
          unidadReferencia: '',
          indicadorFacturacion: '4',
          indicadorBienOServ: '1',
          nombreItem: 'MAIZ EL MAIZAL',
          descripcionItem: '',
          precioUnitarioReferencia: '',
          precioUnitario: '350.0000',
          descuentoMonto: '',
          subCantidades: [],
          gradosAlcohol: '',
          subDescuentos: [],
          recargoMonto: '',
          subRecargos: [],
          impuestosAdicionales: [],
          montoItem: '7000.00'),
      EcfDetailsModel(
          cantidad: '30.00',
          unidadMedida: '46',
          cantidadReferencia: '',
          unidadReferencia: '',
          indicadorFacturacion: '2',
          indicadorBienOServ: '1',
          nombreItem: 'CAF¿ SANTO DOMINGO',
          descripcionItem: '',
          precioUnitarioReferencia: '',
          precioUnitario: '400.0000',
          descuentoMonto: '',
          subCantidades: [],
          gradosAlcohol: '',
          subDescuentos: [],
          recargoMonto: '',
          subRecargos: [],
          impuestosAdicionales: [],
          montoItem: '12000.00'),
    ];

    EcfModel ecf = EcfModel(
      tipoEcf: EcfType.e31,
      tempDirName: kTempDirName, // antes: 'climatic'
      numeroComprobante: 'E310000000006',
      codigoModificacion: '',
      fechaEmision: '01-04-2020',
      fechaVencimiento: kfechaVencimiento, // antes: '31-12-2028'
      fechaEmisionNcfModificado: '',
      razonModificacion: '',
      tipoIngreso: '01',
      tipoPago: '1',
      formasDePagos: [FormaDePago('1', '228460.50')],
      sucursal: '',
      municipio: '010100',
      provincia: '010000',
      telefonoEmisor1: '809-472-7676',
      telefonoEmisor2: '809-491-1918',
      telefonoEmisor3: '',
      totalPaginas: '',
      rncEmisor: kRncEmisor, // antes: '130897271'
      razonSocialEmisor: 'DOCUMENTOS ELECTRONICOS DE 02',
      nombreComercial: 'DOCUMENTOS ELECTRONICOS DE 02',
      direccionEmisor: 'AVE. ISABEL AGUIAR NO. 269, ZONA INDUSTRIAL DE HERRERA',
      correoEmisor:
          'DOCUMENTOSELECTRONICOSDE0612345678969789+9000000000000000000000000000001@123.COM',
      website: 'www.facturaelectronica.com',
      actividadEconomica: '',
      codigoVendedor:
          'AA0000000100000000010000000002000000000300000000050000000006',
      informacionAdicionalEmisor: '',
      rncComprador: '131880681',
      razonSocialComprador: 'DOCUMENTOS ELECTRONICOS DE 03',
      nombreComprador: '',
      contactoComprador: 'MARCOS LATIPLOL',
      correoComprador: 'MARCOSLATIPLOL@KKKK.COM',
      telefonoAdicional: '',
      direccionComprador:
          'CALLE JACINTO DE LA CONCHA FELIZ ESQUINA 27 DE FEBRERO,FRENTE A DOMINO',
      municipioComprador: '010100',
      provinciaComprador: '010000',
      codigoInternoComprador: '10633440',
      fechaEntrega: '10-10-2020',
      fechaEmbarque: '',
      fechaOrdenCompra: '10-11-2018',
      numeroOrdenCompra: '4500352238',
      numeroFacturaInterna: '123456789016',
      numeroPedidoInterno: '123456789016',
      numeroContenedor: '',
      numeroReferencia: '',
      numeroEmbarque: '',
      pesoBruto: '',
      pesoNeto: '',
      unidadPesoBruto: '',
      unidadPesoNeto: '',
      cantidadBulto: '',
      unidadBulto: '',
      volumenBulto: '',
      unidadVolumen: '',
      zonaVenta: 'NORTE',
      rutaVenta: '',
      indicadorMontoGravado: '0',
      totalGravado: '133975.00',
      totalGravado18: '69975.00',
      totalGravado16: '64000.00',
      totalGravadoTasa0: '',
      montoExento: '71650.00',
      totalItbis: '22835.50',
      totalItbis18: '12595.50',
      totalItbis16: '10240.00',
      totalItbisTasa0: '',
      itbis1: '18',
      itbis2: '16',
      itbis3: '',
      montoPeriodo: '228460.50',
      montoAvancePago: '',
      valorPagar: '228460.50',
      totalItbisRetencion: '',
      totalIsrRetencion: '',
      montoImpuestoAdicional: '',
      impuestosAdicionales: [],
      montoTotal: '228460.50',
      terminoPago: '',
      bancoPago: '',
      paginas: [],
      items: items,
      privateKey: '',
      certBase64: ''
    );

EcfModel kE310000000006 = ecf;
