
import 'package:ecf_dgii/settings.dart';
import 'package:ecf_dgii/src/models/ecf.model.dart';
import 'package:ecf_dgii/src/types/ecf.dart';

    List<EcfDetailsModel> items = [
      EcfDetailsModel(
          cantidad: '236.00',
          unidadMedida: '43',
          indicadorFacturacion: '1',
          indicadorBienOServ: '1',
          nombreItem: 'LAPICES',
          descripcionItem: '',
          precioUnitario: '35.0000',
          descuentoMonto: '',
          subDescuentos: [],
          recargoMonto: '',
          subRecargos: [],
          otraMonedaDetalles: [],
          impuestosAdicionales: [],
          montoItem: '8260.00'),
      EcfDetailsModel(
          cantidad: '527.00',
          unidadMedida: '6',
          indicadorFacturacion: '2',
          indicadorBienOServ: '1',
          nombreItem: 'GALLETAS',
          descripcionItem: '',
          precioUnitario: '3650.0000',
          descuentoMonto: '',
          subDescuentos: [],
          recargoMonto: '',
          subRecargos: [],
          otraMonedaDetalles: [],
          impuestosAdicionales: [],
          montoItem: '1923550.00'),
      EcfDetailsModel(
          cantidad: '174.00',
          unidadMedida: '31',
          indicadorFacturacion: '3',
          indicadorBienOServ: '1',
          nombreItem: 'PAN',
          descripcionItem: '',
          precioUnitario: '157.0000',
          descuentoMonto: '',
          subDescuentos: [],
          recargoMonto: '',
          subRecargos: [],
          otraMonedaDetalles: [],
          impuestosAdicionales: [],
          montoItem: '27318.00'),
      EcfDetailsModel(
          cantidad: '128.00',
          unidadMedida: '47',
          indicadorFacturacion: '2',
          indicadorBienOServ: '1',
          nombreItem: 'LECHE',
          descripcionItem: '',
          precioUnitario: '97.0000',
          descuentoMonto: '',
          subDescuentos: [],
          recargoMonto: '',
          subRecargos: [],
          otraMonedaDetalles: [],
          impuestosAdicionales: [],
          montoItem: '12416.00')
    ];

    EcfModel ecf = EcfModel(
      tipoEcf: EcfType.e32,
      tempDirName: kTempDirName, // antes: 'elcrujiente'
      indicadorMontoGravado: '0',
      indicadorNotaCredito: '',
      rncOtroContribuyente: '',
      numeroComprobante: 'E320000000005',
      numeroComprobanteModificado: '',
      codigoModificacion: '',
      fechaEmision: '01-04-2020',
      fechaVencimiento: '', // vacío en facturas de consumo
      fechaEmisionNcfModificado: '',
      razonModificacion: '',
      tipoIngreso: '01',
      tipoPago: '1',
      formasDePagos: [FormaDePago('1', '2282785.36')],
      sucursal: '',
      municipio: '010100',
      provincia: '010000',
      telefonoEmisor1: '809-472-7676',
      telefonoEmisor2: '809-491-1918',
      telefonoEmisor3: '',
      totalPaginas: '',
      rncEmisor: kRncEmisor, // antes: '133585456'
      razonSocialEmisor: 'DOCUMENTOS ELECTRONICOS DE 02',
      nombreComercial: 'DOCUMENTOS ELECTRONICOS DE 02',
      direccionEmisor: 'AVE. ISABEL AGUIAR NO. 269, ZONA INDUSTRIAL DE HERRERA',
      correoEmisor:
          'DOCUMENTOSELECTRONICOSDE0612345678969789+9000000000000000000000000000001@123.COM',
      website: 'www.facturaelectronica.com',
      actividadEconomica: '',
      codigoVendedor:
          'AA0000000100000000010000000002000000000300000000050000000006',
      informacionAdicionalEmisor: '',
      rncComprador: '131880681',
      identificadorExtranjero: '',
      razonSocialComprador: 'DOCUMENTOS ELECTRONICOS DE 03',
      nombreComprador: '',
      contactoComprador: 'MARCOS LATIPLOL',
      correoComprador: 'MARCOSLATIPLOL@KKKK.COM',
      telefonoAdicional: '',
      direccionComprador:
          'CALLE JACINTO DE LA CONCHA FELIZ ESQUINA 27 DE FEBRERO,FRENTE A DOMINO',
      municipioComprador: '010100',
      provinciaComprador: '010000',
      codigoInternoComprador: '10633440',
      fechaEmbarque: '08-06-2020',
      numeroEmbarque: '1550523',
      numeroContenedor: '1025536',
      numeroReferencia: '121517',
      pesoBruto: '25.00',
      pesoNeto: '24.50',
      unidadPesoBruto: '23',
      unidadPesoNeto: '23',
      cantidadBulto: '1.00',
      unidadBulto: '6',
      volumenBulto: '1.00',
      unidadVolumen: '6',
      fechaEntrega: '10-10-2020',
      fechaOrdenCompra: '10-11-2018',
      numeroOrdenCompra: '4500352238',
      numeroFacturaInterna: '123456789016',
      numeroPedidoInterno: '123456789016',
      zonaVenta: 'NORTE',
      rutaVenta: '',
      paisDestino: '',
      conductor: '',
      documentoTransporte: '',
      ficha: '',
      placa: '',
      rutaTransporte: '',
      zonaTransporte: '',
      numeroAlbaran: '',
      totalGravado: '1971544.00',
      totalGravado18: '8260.00',
      totalGravado16: '1935966.00',
      totalGravadoTasa0: '27318.00',
      montoExento: '',
      totalItbis: '311241.36',
      totalItbis18: '1486.80',
      totalItbis16: '309754.56',
      totalItbisTasa0: '0.00',
      itbis1: '18',
      itbis2: '16',
      itbis3: '0',
      montoTotal: '2282785.36',
      montoNoFacturable: '',
      montoPeriodo: '2282785.36',
      montoAvancePago: '',
      valorPagar: '2282785.36',
      tipoMoneda: '',
      tipoCambio: '',
      montoGravadoTotalOtraMoneda: '',
      montoGravadoTotalOtraMoneda1: '',
      montoGravadoTotalOtraMoneda2: '',
      montoGravadoTotalOtraMoneda3: '',
      totalItbisOtraMoneda: '',
      totalItbis1OtraMoneda: '',
      totalItbis2OtraMoneda: '',
      totalItbis3OtraMoneda: '',
      montoExentoOtraMoneda: '',
      montoTotalOtraMoneda: '',
      totalItbisRetencion: '',
      totalIsrRetencion: '',
      montoImpuestoAdicional: '',
      impuestosAdicionales: [],
      terminoPago: '',
      bancoPago: '',
      paginas: [],
      items: items,
      privateKey: '',
      certBase64: ''
    );


EcfModel kE320000000005 = ecf;
    