import 'dart:io';
import 'package:ecf_dgii/settings.dart';
import 'package:ecf_dgii/src/models/ecf.model.dart';
import 'package:ecf_dgii/src/types/ecf.dart';
import 'package:ecf_dgii/src/utils/directories.dart';
import 'package:ecf_dgii/src/utils/generate.endpoint.dart';
import 'package:ecf_dgii/src/utils/p12.parser.dart';
import 'package:intl/intl.dart';
import 'package:path/path.dart' as path;


    List<EcfDetailsModel> items = [
      EcfDetailsModel(
          cantidad: '100.00',
          unidadMedida: '23',
          indicadorFacturacion: '1',
          indicadorBienOServ: '1',
          nombreItem: 'BLOCK',
          descripcionItem: '',
          precioUnitario: '450.0000',
          descuentoMonto: '',
          subDescuentos: [],
          recargoMonto: '',
          subRecargos: [],
          otraMonedaDetalles: [],
          impuestosAdicionales: [],
          montoItem: '45000.00'),
      EcfDetailsModel(
          cantidad: '300.00',
          unidadMedida: '23',
          indicadorFacturacion: '1',
          indicadorBienOServ: '1',
          nombreItem: 'VARILLAS',
          descripcionItem: '',
          precioUnitario: '350.0000',
          descuentoMonto: '',
          subDescuentos: [],
          recargoMonto: '',
          subRecargos: [],
          otraMonedaDetalles: [],
          impuestosAdicionales: [],
          montoItem: '105000.00'),
      EcfDetailsModel(
          cantidad: '200.00',
          unidadMedida: '23',
          indicadorFacturacion: '1',
          indicadorBienOServ: '1',
          nombreItem: 'CINZ',
          descripcionItem: '',
          precioUnitario: '425.0000',
          descuentoMonto: '',
          subDescuentos: [],
          recargoMonto: '',
          subRecargos: [],
          otraMonedaDetalles: [],
          impuestosAdicionales: [],
          montoItem: '85000.00'),
      EcfDetailsModel(
          cantidad: '50.00',
          unidadMedida: '23',
          indicadorFacturacion: '1',
          indicadorBienOServ: '1',
          nombreItem: 'CLAVOS DE MEDIA',
          descripcionItem: '',
          precioUnitario: '550.0000',
          descuentoMonto: '',
          subDescuentos: [],
          recargoMonto: '',
          subRecargos: [],
          otraMonedaDetalles: [],
          impuestosAdicionales: [],
          montoItem: '27500.00'),
      EcfDetailsModel(
          cantidad: '50.00',
          unidadMedida: '23',
          indicadorFacturacion: '1',
          indicadorBienOServ: '1',
          nombreItem: 'CLAVOS DE CUARTA',
          descripcionItem: '',
          precioUnitario: '325.0000',
          descuentoMonto: '',
          subDescuentos: [],
          recargoMonto: '',
          subRecargos: [],
          otraMonedaDetalles: [],
          impuestosAdicionales: [],
          montoItem: '16250.00')
    ];

   EcfModel ecf = EcfModel(
      tipoEcf: EcfType.e32,
      tempDirName: kTempDirName,          // antes: 'arenal'
      indicadorMontoGravado: '0',
      indicadorNotaCredito: '',
      rncOtroContribuyente: '',
      numeroComprobante: 'E320000000003', // comprobante actual
      numeroComprobanteModificado: '',
      codigoModificacion: '',
      fechaEmision: '01-04-2020',
      fechaVencimiento: '', // antes: '' (puedes definirlo en settings)
      fechaEmisionNcfModificado: '',
      razonModificacion: '',
      tipoIngreso: '01',
      tipoPago: '1',
      formasDePagos: [FormaDePago('1', '328925.00')],
      sucursal: '',
      municipio: '010100',
      provincia: '010000',
      telefonoEmisor1: '809-472-7676',
      telefonoEmisor2: '809-491-1918',
      telefonoEmisor3: '',
      totalPaginas: '',
      rncEmisor: kRncEmisor,              // antes: '123006624'
      razonSocialEmisor: 'DOCUMENTOS ELECTRONICOS DE 02',
      nombreComercial: 'DOCUMENTOS ELECTRONICOS DE 02',
      direccionEmisor: 'AVE. ISABEL AGUIAR NO. 269, ZONA INDUSTRIAL DE HERRERA',
      correoEmisor: 'DOCUMENTOSELECTRONICOSDE0612345678969789+9000000000000000000000000000001@123.COM',
      website: 'www.facturaelectronica.com',
      actividadEconomica: '',
      codigoVendedor: 'AA0000000100000000010000000002000000000300000000050000000006',
      informacionAdicionalEmisor: '',
      rncComprador: '131880681',
      identificadorExtranjero: '',
      razonSocialComprador: 'DOCUMENTOS ELECTRONICOS DE 03',
      nombreComprador: '',
      contactoComprador: 'MARCOS LATIPLOL',
      correoComprador: 'MARCOSLATIPLOL@KKKK.COM',
      telefonoAdicional: '',
      direccionComprador: 'CALLE JACINTO DE LA CONCHA FELIZ ESQUINA 27 DE FEBRERO,FRENTE A DOMINO',
      municipioComprador: '010100',
      provinciaComprador: '010000',
      codigoInternoComprador: '10633440',
      numeroContenedor: '',
      numeroReferencia: '',
      fechaEntrega: '10-10-2020',
      fechaOrdenCompra: '10-11-2018',
      numeroOrdenCompra: '4500352238',
      numeroFacturaInterna: '123456789016',
      numeroPedidoInterno: '123456789016',
      zonaVenta: 'NORTE',
      rutaVenta: '',
      conductor: 'Rafael Perez',
      documentoTransporte: '363636',
      ficha: 'J-1234',
      placa: 'A639689',
      rutaTransporte: 'B-Sur',
      zonaTransporte: 'Interior-1',
      numeroAlbaran: '3634258',
      totalGravado: '278750.00',
      totalGravado18: '278750.00',
      totalGravado16: '',
      totalGravadoTasa0: '',
      montoExento: '',
      totalItbis: '50175.00',
      totalItbis18: '50175.00',
      totalItbis16: '',
      totalItbisTasa0: '',
      itbis1: '18',
      itbis2: '',
      itbis3: '',
      montoTotal: '328925.00',
      montoPeriodo: '328925.00',
      valorPagar: '328925.00',
      impuestosAdicionales: [],
      paginas: [],
      items: items,
      privateKey: '',
      certBase64: ''
    );


EcfModel kE320000000003 = ecf;
  