
import 'package:ecf_dgii/settings.dart';
import 'package:ecf_dgii/src/models/ecf.model.dart';
import 'package:ecf_dgii/src/types/ecf.dart';
   List<EcfDetailsModel> items = [
      EcfDetailsModel(
          cantidad: '1',
          unidadMedida: '55',
          indicadorFacturacion: '1',
          indicadorBienOServ: '1',
          nombreItem: 'Articulos de belleza',
          descripcionItem: '',
          precioUnitario: '10000.00',
          descuentoMonto: '',
          subDescuentos: [],
          recargoMonto: '',
          subRecargos: [],
          otraMonedaDetalles: [],
          impuestosAdicionales: [],
          montoItem: '10000.00'),
      EcfDetailsModel(
          cantidad: '1',
          unidadMedida: '23',
          indicadorFacturacion: '1',
          indicadorBienOServ: '1',
          nombreItem: 'Queso',
          descripcionItem: '',
          precioUnitario: '100.00',
          descuentoMonto: '',
          subDescuentos: [],
          recargoMonto: '',
          subRecargos: [],
          otraMonedaDetalles: [],
          impuestosAdicionales: [],
          montoItem: '100.00'),
    ];

    EcfModel ecf = EcfModel(
        tipoEcf: EcfType.e32,
        tempDirName: kTempDirName,
        indicadorMontoGravado: '0',
        indicadorNotaCredito: '',
        rncOtroContribuyente: '',
        numeroComprobante: 'E320000000014',
        numeroComprobanteModificado: '',
        codigoModificacion: '',
        fechaEmision: '01-04-2020',
        fechaVencimiento: '',
        fechaEmisionNcfModificado: '',
        razonModificacion: '',
        tipoIngreso: '01',
        tipoPago: '1',
        formasDePagos: [],
        sucursal: '',
        municipio: '',
        provincia: '',
        telefonoEmisor1: '809-472-7676',
        telefonoEmisor2: '',
        telefonoEmisor3: '',
        totalPaginas: '',
        rncEmisor: kRncEmisor,
        razonSocialEmisor:
            'DOCUMENTOS ELECTRONICOS PRUEBA FACTURA DE CONSUMO MENOR 250MIL',
        nombreComercial: 'DOCUMENTOS ELECTRONICOS',
        direccionEmisor:
            'AVE. ISABEL AGUIAR NO. 269, ZONA INDUSTRIAL DE HERRERA',
        correoEmisor: 'DOCUMENTOSELECTRONICOS@123.COM',
        website: '',
        actividadEconomica: '',
        codigoVendedor: '',
        informacionAdicionalEmisor: '',
        rncComprador: '131880681',
        identificadorExtranjero: '',
        razonSocialComprador: 'DOCUMENTOS ELECTRONICOS DE 03',
        nombreComprador: '',
        contactoComprador: '',
        correoComprador: 'DOCUMENTOSELECTRONICOSDE0612345678969789@123.COM',
        telefonoAdicional: '809-472-7676',
        direccionComprador:
            'AVE. ISABEL AGUIAR NO. 269, ZONA INDUSTRIAL DE HERRERA',
        municipioComprador: '170203',
        provinciaComprador: '170000',
        codigoInternoComprador: '',
        numeroContenedor: '',
        numeroReferencia: '',
        fechaEntrega: '',
        fechaOrdenCompra: '',
        numeroOrdenCompra: '',
        numeroFacturaInterna: '',
        numeroPedidoInterno: '',
        zonaVenta: '',
        rutaVenta: '',
        paisDestino: '',
        conductor: '',
        documentoTransporte: '',
        ficha: '',
        placa: '',
        rutaTransporte: '',
        zonaTransporte: '',
        numeroAlbaran: '',
        totalGravado: '10100.00',
        totalGravado18: '10100.00',
        totalGravado16: '',
        totalGravadoTasa0: '',
        montoExento: '',
        totalItbis: '1818.00',
        totalItbis18: '1818.00',
        totalItbis16: '',
        totalItbisTasa0: '',
        itbis1: '18',
        itbis2: '',
        itbis3: '',
        montoTotal: '11918.00',
        montoNoFacturable: '',
        montoPeriodo: '',
        montoAvancePago: '',
        valorPagar: '',
        tipoMoneda: '',
        tipoCambio: '',
        montoGravadoTotalOtraMoneda: '',
        montoGravadoTotalOtraMoneda1: '',
        montoGravadoTotalOtraMoneda2: '',
        montoGravadoTotalOtraMoneda3: '',
        totalItbisOtraMoneda: '',
        totalItbis1OtraMoneda: '',
        totalItbis2OtraMoneda: '',
        totalItbis3OtraMoneda: '',
        montoExentoOtraMoneda: '',
        montoTotalOtraMoneda: '',
        totalItbisRetencion: '',
        totalIsrRetencion: '',
        montoImpuestoAdicional: '',
        impuestosAdicionales: [],
        terminoPago: '',
        bancoPago: '',
        paginas: [],
        items: items,
        privateKey: '',
        certBase64: '');
  
  EcfModel kE320000000014 = ecf;
