
import 'package:ecf_dgii/settings.dart';
import 'package:ecf_dgii/src/models/ecf.model.dart';
import 'package:ecf_dgii/src/types/ecf.dart';

 final fechaEmision = '02-12-2018';

    List<EcfDetailsModel> items = [
      EcfDetailsModel(
          cantidad: '1.00',
          unidadMedida: '',
          indicadorFacturacion: '0',
          indicadorBienOServ: '2',
          nombreItem: 'AGUACATE CRIOLLO ACTUALIZADO',
          descripcionItem: '',
          precioUnitario: '1.00',
          descuentoMonto: '',
          subDescuentos: [],
          impuestosAdicionales: [],
          otraMonedaDetalles: [],
          montoItem: '1.00'),
    ];

    EcfModel ecf = EcfModel(
        tipoEcf: EcfType.e34,
        tempDirName: kTempDirName,
        indicadorMontoGravado: '',
        indicadorNotaCredito: '0',
        rncOtroContribuyente: '',
        numeroComprobante: 'E340000000018',
        numeroComprobanteModificado: 'E460000000009',
        codigoModificacion: '2',
        fechaEmision: fechaEmision,
        fechaVencimiento: '',
        fechaEmisionNcfModificado: '01-12-2018',
        razonModificacion: 'Error en datos',
        tipoIngreso: '01',
        tipoPago: '1',
        formasDePagos: [],
        sucursal: '',
        direccionEmisor: 'DOCUMENTOS ELECTRONICOS DE 02',
        municipio: '',
        provincia: '',
        telefonoEmisor1: '',
        telefonoEmisor2: '',
        telefonoEmisor3: '',
        totalPaginas: '',
        rncEmisor: kRncEmisor,
        razonSocialEmisor: 'DOCUMENTOS ELECTRONICOS DE 02',
        nombreComercial: '',
        correoEmisor: '',
        website: '',
        actividadEconomica: '',
        codigoVendedor: '',
        informacionAdicionalEmisor: '',
        rncComprador: '131880681',
        identificadorExtranjero: '',
        razonSocialComprador: 'DOCUMENTOS ELECTRONICOS DE 01',
        nombreComprador: '',
        contactoComprador: '',
        correoComprador: '',
        telefonoAdicional: '',
        direccionComprador: '',
        municipioComprador: '',
        provinciaComprador: '',
        codigoInternoComprador: '',
        numeroContenedor: '',
        numeroReferencia: '',
        fechaEntrega: '',
        fechaOrdenCompra: '',
        numeroOrdenCompra: '',
        numeroFacturaInterna: '',
        numeroPedidoInterno: '',
        zonaVenta: '',
        rutaVenta: '',
        paisDestino: '',
        conductor: '',
        documentoTransporte: '',
        ficha: '',
        placa: '',
        rutaTransporte: '',
        zonaTransporte: '',
        numeroAlbaran: '',
        totalGravado: '',
        totalGravado18: '',
        totalGravado16: '',
        totalGravadoTasa0: '',
        montoExento: '',
        totalItbis: '',
        totalItbis18: '',
        totalItbis16: '',
        totalItbisTasa0: '',
        itbis1: '',
        itbis2: '',
        itbis3: '',
        montoTotal: '0.00',
        montoNoFacturable: '1.00',
        montoPeriodo: '',
        montoAvancePago: '',
        valorPagar: '',
        tipoMoneda: '',
        tipoCambio: '',
        montoGravadoTotalOtraMoneda: '',
        montoGravadoTotalOtraMoneda1: '',
        montoGravadoTotalOtraMoneda2: '',
        montoGravadoTotalOtraMoneda3: '',
        totalItbisOtraMoneda: '',
        totalItbis1OtraMoneda: '',
        totalItbis2OtraMoneda: '',
        totalItbis3OtraMoneda: '',
        montoExentoOtraMoneda: '',
        montoTotalOtraMoneda: '',
        totalItbisRetencion: '',
        totalIsrRetencion: '',
        montoImpuestoAdicional: '',
        impuestosAdicionales: [],
        terminoPago: '',
        bancoPago: '',
        paginas: [],
        items: items,
        privateKey: '',
        certBase64: '');
    
    EcfModel kE340000000018 = ecf;
    