import 'package:ecf_dgii/ecf_dgii.dart';
import 'package:ecf_dgii/settings.dart';

final fechaEmision = '01-04-2020';

List<EcfDetailsModel> items = [
  EcfDetailsModel(
      cantidad: '1.00',
      unidadMedida: '43',
      indicadorFacturacion: '4',
      indicadorBienOServ: '2',
      nombreItem: 'Gastos de Oficina',
      descripcionItem: '',
      precioUnitario: '115000.0000',
      descuentoMonto: '',
      subDescuentos: [],
      montoItem: '115000.00',
      codigos: [TipoCodigo(tipoCodigo: 'Interno', codigoItem: '1521')],
      impuestosAdicionales: []),
  EcfDetailsModel(
      cantidad: '1.00',
      unidadMedida: '43',
      indicadorFacturacion: '4',
      indicadorBienOServ: '2',
      nombreItem: 'Gastos de Transporte',
      descripcionItem: '',
      precioUnitario: '79000.00',
      descuentoMonto: '',
      subDescuentos: [],
      montoItem: '79000.00',
      codigos: [TipoCodigo(tipoCodigo: 'Interno', codigoItem: '1521')],
      impuestosAdicionales: []),
  EcfDetailsModel(
      cantidad: '1.00',
      unidadMedida: '43',
      indicadorFacturacion: '4',
      indicadorBienOServ: '2',
      nombreItem: 'Mantenimiento',
      descripcionItem: '',
      precioUnitario: '23980.00',
      descuentoMonto: '',
      subDescuentos: [],
      montoItem: '23980.00',
      codigos: [TipoCodigo(tipoCodigo: 'Interno', codigoItem: '1521')],
      impuestosAdicionales: []),
  EcfDetailsModel(
      cantidad: '2.00',
      unidadMedida: '43',
      indicadorFacturacion: '4',
      indicadorBienOServ: '2',
      nombreItem: 'Gastos varios',
      descripcionItem: '',
      precioUnitario: '17895.0000',
      descuentoMonto: '',
      subDescuentos: [],
      montoItem: '35790.00',
      codigos: [TipoCodigo(tipoCodigo: 'Interno', codigoItem: '1521')],
      impuestosAdicionales: []),
];

EcfModel ecf = EcfModel(
    tipoEcf: EcfType.e43,
    tempDirName: kTempDirName,
    indicadorMontoGravado: '',
    numeroComprobante: 'E430000000007',
    codigoModificacion: '',
    fechaEmision: fechaEmision,
    fechaVencimiento: kfechaVencimiento,
    fechaEmisionNcfModificado: '',
    razonModificacion: '',
    tipoIngreso: '',
    tipoPago: '',
    formasDePagos: [],
    sucursal: '',
    direccionEmisor: 'AVE. ISABEL AGUIAR NO. 269, ZONA INDUSTRIAL DE HERRERA',
    municipio: '010100',
    provincia: '010000',
    telefonoEmisor1: '809-472-7676',
    telefonoEmisor2: '809-491-1918',
    telefonoEmisor3: '',
    totalPaginas: '',
    rncEmisor: kRncEmisor,
    razonSocialEmisor: 'DOCUMENTOS ELECTRONICOS DE 02',
    nombreComercial: 'DOCUMENTOS ELECTRONICOS DE 02',
    correoEmisor:
        'DOCUMENTOSELECTRONICOSDE0612345678969789+9000000000000000000000000000001@123.COM',
    website: 'www.facturaelectronica.com',
    actividadEconomica: '',
    codigoVendedor: '',
    informacionAdicionalEmisor: '',
    rncComprador: '',
    razonSocialComprador: '',
    nombreComprador: '',
    contactoComprador: '',
    correoComprador: '',
    telefonoAdicional: '',
    direccionComprador: '',
    municipioComprador: '',
    provinciaComprador: '',
    codigoInternoComprador: '',
    fechaEntrega: '',
    fechaOrdenCompra: '',
    numeroOrdenCompra: '',
    numeroFacturaInterna: '',
    numeroPedidoInterno: '',
    zonaVenta: '',
    rutaVenta: '',
    totalGravado: '',
    totalGravado18: '',
    totalGravado16: '',
    totalGravadoTasa0: '',
    montoExento: '253770.00',
    totalItbis: '',
    totalItbis18: '',
    totalItbis16: '',
    totalItbisTasa0: '',
    itbis1: '',
    itbis2: '',
    itbis3: '',
    montoTotal: '253770.00',
    montoPeriodo: '253770.00',
    montoAvancePago: '',
    valorPagar: '253770.00',
    totalItbisRetencion: '',
    totalIsrRetencion: '',
    montoImpuestoAdicional: '',
    impuestosAdicionales: [],
    terminoPago: '',
    bancoPago: '',
    paginas: [],
    items: items,
    privateKey: '',
    certBase64: '');

EcfModel kE430000000007 = ecf;