
import 'package:ecf_dgii/settings.dart';
import 'package:ecf_dgii/src/models/ecf.model.dart';
import 'package:ecf_dgii/src/types/ecf.dart';

    final fechaEmision = '01-04-2020';

    List<EcfDetailsModel> items = [
      EcfDetailsModel(
          cantidad: '1',
          unidadMedida: '43',
          codigos: [TipoCodigo(tipoCodigo: 'Interno', codigoItem: '1521')],
          indicadorFacturacion: '4',
          indicadorBienOServ: '2',
          nombreItem: 'Gastos de Oficina',
          descripcionItem: '',
          precioUnitario: '10000.0000',
          descuentoMonto: '',
          subDescuentos: [],
          impuestosAdicionales: [],
          otraMonedaDetalles: [],
          montoItem: '10000.00'),
      EcfDetailsModel(
          cantidad: '1',
          unidadMedida: '43',
          codigos: [TipoCodigo(tipoCodigo: 'Interno', codigoItem: '1522')],
          indicadorFacturacion: '4',
          indicadorBienOServ: '2',
          nombreItem: 'Gastos de Transporte',
          descripcionItem: '',
          precioUnitario: '5000.0000',
          descuentoMonto: '',
          subDescuentos: [],
          impuestosAdicionales: [],
          otraMonedaDetalles: [],
          montoItem: '5000.00'),
      EcfDetailsModel(
          cantidad: '1',
          unidadMedida: '43',
          codigos: [TipoCodigo(tipoCodigo: 'Interno', codigoItem: '1523')],
          indicadorFacturacion: '4',
          indicadorBienOServ: '2',
          nombreItem: 'Mantenimiento',
          descripcionItem: '',
          precioUnitario: '3500.0000',
          descuentoMonto: '',
          subDescuentos: [],
          impuestosAdicionales: [],
          otraMonedaDetalles: [],
          montoItem: '3500.00'),
      EcfDetailsModel(
          cantidad: '2',
          unidadMedida: '43',
          codigos: [TipoCodigo(tipoCodigo: 'Interno', codigoItem: '1524')],
          indicadorFacturacion: '4',
          indicadorBienOServ: '2',
          nombreItem: 'Gastos varios',
          descripcionItem: '',
          precioUnitario: '6500.0000',
          descuentoMonto: '',
          subDescuentos: [],
          impuestosAdicionales: [],
          otraMonedaDetalles: [],
          montoItem: '13000.00'),
      EcfDetailsModel(
          cantidad: '1',
          unidadMedida: '43',
          codigos: [TipoCodigo(tipoCodigo: 'Interno', codigoItem: '1526')],
          indicadorFacturacion: '4',
          indicadorBienOServ: '2',
          nombreItem: 'Gastos menor cuanta',
          descripcionItem: '',
          precioUnitario: '800.0000',
          descuentoMonto: '',
          subDescuentos: [],
          impuestosAdicionales: [],
          otraMonedaDetalles: [],
          montoItem: '800.00'),
    ];

   EcfModel ecf = EcfModel(
      tipoEcf: EcfType.e43,
      tempDirName: kTempDirName,          // antes: 'arenal'
      indicadorMontoGravado: '',
      indicadorNotaCredito: '',
      rncOtroContribuyente: '',
      numeroComprobante: 'E430000000012',
      numeroComprobanteModificado: '',
      codigoModificacion: '',
      fechaEmision: fechaEmision,
      fechaVencimiento: kfechaVencimiento, // antes: '31-12-2028'
      fechaEmisionNcfModificado: '',
      razonModificacion: '',
      tipoIngreso: '',
      tipoPago: '1',
      formasDePagos: [],
      sucursal: '',
      municipio: '010100',
      provincia: '010000',
      telefonoEmisor1: '809-472-7676',
      telefonoEmisor2: '809-491-1918',
      telefonoEmisor3: '',
      totalPaginas: '',
      rncEmisor: kRncEmisor,              // antes: '123006624'
      razonSocialEmisor: 'DOCUMENTOS ELECTRONICOS DE 02',
      nombreComercial: 'DOCUMENTOS ELECTRONICOS DE 02',
      direccionEmisor: 'AVE. ISABEL AGUIAR NO. 269, ZONA INDUSTRIAL DE HERRERA',
      correoEmisor: 'DOCUMENTOSELECTRONICOSDE0612345678969789+9000000000000000000000000000001@123.COM',
      website: 'www.facturaelectronica.com',
      actividadEconomica: '',
      codigoVendedor: '',
      informacionAdicionalEmisor: '',
      rncComprador: '',
      identificadorExtranjero: '',
      razonSocialComprador: '',
      nombreComprador: '',
      contactoComprador: '',
      correoComprador: '',
      telefonoAdicional: '',
      direccionComprador: '',
      municipioComprador: '',
      provinciaComprador: '',
      codigoInternoComprador: '',
      numeroContenedor: '',
      numeroReferencia: '',
      fechaEntrega: '',
      fechaOrdenCompra: '',
      numeroOrdenCompra: '',
      numeroFacturaInterna: '',
      numeroPedidoInterno: '',
      zonaVenta: '',
      rutaVenta: '',
      paisDestino: '',
      conductor: '',
      documentoTransporte: '',
      ficha: '',
      placa: '',
      rutaTransporte: '',
      zonaTransporte: '',
      numeroAlbaran: '',
      totalGravado: '',
      totalGravado18: '',
      totalGravado16: '',
      totalGravadoTasa0: '',
      montoExento: '32300.00',
      totalItbis: '',
      totalItbis18: '',
      totalItbis16: '',
      totalItbisTasa0: '',
      itbis1: '',
      itbis2: '',
      itbis3: '',
      montoTotal: '32300.00',
      montoNoFacturable: '',
      montoPeriodo: '',
      montoAvancePago: '',
      valorPagar: '',
      tipoMoneda: '',
      tipoCambio: '',
      montoGravadoTotalOtraMoneda: '',
      montoGravadoTotalOtraMoneda1: '',
      montoGravadoTotalOtraMoneda2: '',
      montoGravadoTotalOtraMoneda3: '',
      totalItbisOtraMoneda: '',
      totalItbis1OtraMoneda: '',
      totalItbis2OtraMoneda: '',
      totalItbis3OtraMoneda: '',
      montoExentoOtraMoneda: '',
      montoTotalOtraMoneda: '',
      totalItbisRetencion: '',
      totalIsrRetencion: '',
      montoImpuestoAdicional: '',
      impuestosAdicionales: [],
      terminoPago: '',
      bancoPago: '',
      paginas: [],
      items: items,
      privateKey: '',
      certBase64: ''
    );

    EcfModel kE430000000012 = ecf;

    