import 'package:ecf_dgii/ecf_dgii.dart';
import 'package:ecf_dgii/settings.dart';

final fechaEmision = '01-04-2020';

List<EcfDetailsModel> items = [
  EcfDetailsModel(
      cantidad: '23.00',
      unidadMedida: '43',
      indicadorFacturacion: '1',
      indicadorBienOServ: '1',
      nombreItem: 'LAPICES',
      descripcionItem: '',
      precioUnitario: '35.0000',
      descuentoMonto: '',
      subDescuentos: [],
      impuestosAdicionales: [],
      otraMonedaDetalles: [
        OtraMonedaDetalle(
            precioOtraMoneda: '3.55',
            descuentoOtraMoneda: '',
            recargoOtraMoneda: '',
            montoItemOtraMoneda: '81.65')
      ],
      montoItem: '805.00'),
  EcfDetailsModel(
      cantidad: '547.00',
      unidadMedida: '6',
      indicadorFacturacion: '2',
      indicadorBienOServ: '1',
      nombreItem: 'GALLETAS',
      descripcionItem: '',
      precioUnitario: '145.0000',
      descuentoMonto: '',
      subDescuentos: [],
      impuestosAdicionales: [],
      otraMonedaDetalles: [
        OtraMonedaDetalle(
            precioOtraMoneda: '4.55',
            descuentoOtraMoneda: '',
            recargoOtraMoneda: '',
            montoItemOtraMoneda: '2488.85')
      ],
      montoItem: '79315.00'),
  EcfDetailsModel(
      cantidad: '14.00',
      unidadMedida: '31',
      indicadorFacturacion: '3',
      indicadorBienOServ: '1',
      nombreItem: 'PAN',
      descripcionItem: '',
      precioUnitario: '55.0000',
      descuentoMonto: '',
      subDescuentos: [],
      impuestosAdicionales: [],
      otraMonedaDetalles: [
        OtraMonedaDetalle(
            precioOtraMoneda: '2.55',
            descuentoOtraMoneda: '',
            recargoOtraMoneda: '',
            montoItemOtraMoneda: '35.70')
      ],
      montoItem: '770.00'),
  EcfDetailsModel(
      cantidad: '25.00',
      unidadMedida: '24',
      indicadorFacturacion: '1',
      indicadorBienOServ: '1',
      nombreItem: 'SANDWICH',
      descripcionItem: '',
      precioUnitario: '65.0000',
      descuentoMonto: '',
      subDescuentos: [],
      impuestosAdicionales: [],
      otraMonedaDetalles: [
        OtraMonedaDetalle(
            precioOtraMoneda: '1.75',
            descuentoOtraMoneda: '',
            recargoOtraMoneda: '',
            montoItemOtraMoneda: '43.75')
      ],
      montoItem: '1625.00'),
  EcfDetailsModel(
      cantidad: '35.00',
      unidadMedida: '47',
      indicadorFacturacion: '2',
      indicadorBienOServ: '1',
      nombreItem: 'SALSA',
      descripcionItem: '',
      precioUnitario: '25.0000',
      descuentoMonto: '',
      subDescuentos: [],
      impuestosAdicionales: [],
      otraMonedaDetalles: [],
      montoItem: '875.00'),
];

EcfModel ecf = EcfModel(
    tipoEcf: EcfType.e45,
    tempDirName: kTempDirName,
    indicadorMontoGravado: '0',
    numeroComprobante: 'E450000000011',
    codigoModificacion: '',
    fechaEmision: fechaEmision,
    fechaVencimiento: kfechaVencimiento,
    fechaEmisionNcfModificado: '',
    razonModificacion: 'ANULACION DEL ENCF31 CON SECUENCIA QUE FINALIZA EN 61',
    tipoIngreso: '01',
    tipoPago: '1',
    formasDePagos: [FormaDePago('1', '96657.80')],
    sucursal: '',
    direccionEmisor: 'AVE. ISABEL AGUIAR NO. 269, ZONA INDUSTRIAL DE HERRERA',
    municipio: '010100',
    provincia: '010000',
    telefonoEmisor1: '809-472-7676',
    telefonoEmisor2: '809-491-1918',
    telefonoEmisor3: '',
    totalPaginas: '',
    rncEmisor: kRncEmisor,
    razonSocialEmisor: 'DOCUMENTOS ELECTRONICOS DE 02',
    nombreComercial: 'DOCUMENTOS ELECTRONICOS DE 02',
    correoEmisor:
        'DOCUMENTOSELECTRONICOSDE0612345678969789+9000000000000000000000000000001@123.COM',
    website: 'www.facturaelectronica.com',
    actividadEconomica: '',
    codigoVendedor:
        'AA0000000100000000010000000002000000000300000000050000000006',
    informacionAdicionalEmisor: '',
    rncComprador: '131880681',
    razonSocialComprador: 'DOCUMENTOS ELECTRONICOS DE 03',
    nombreComprador: '',
    contactoComprador: 'MARCOS LATIPLOL',
    correoComprador: 'MARCOSLATIPLOL@KKKK.COM',
    telefonoAdicional: '',
    direccionComprador:
        'CALLE JACINTO DE LA CONCHA FELIZ ESQUINA 27 DE FEBRERO,FRENTE A DOMINO',
    municipioComprador: '010100',
    provinciaComprador: '010000',
    codigoInternoComprador: '10633440',
    fechaEntrega: '10-10-2020',
    fechaOrdenCompra: '10-11-2018',
    numeroOrdenCompra: '4500352238',
    numeroFacturaInterna: '123456789016',
    numeroPedidoInterno: '123456789016',
    numeroContenedor: '',
    numeroReferencia: '',
    zonaVenta: 'NORTE',
    rutaVenta: '',
    conductor: '',
    documentoTransporte: '',
    ficha: '',
    placa: '',
    rutaTransporte: '',
    zonaTransporte: '',
    numeroAlbaran: '',
    totalGravado: '83390.00',
    totalGravado18: '2430.00',
    totalGravado16: '80190.00',
    totalGravadoTasa0: '770.00',
    montoExento: '',
    totalItbis: '13267.80',
    totalItbis18: '437.40',
    totalItbis16: '12830.40',
    totalItbisTasa0: '0.00',
    itbis1: '18',
    itbis2: '16',
    itbis3: '0',
    montoTotal: '96657.80',
    montoNoFacturable: '',
    montoPeriodo: '96657.80',
    montoAvancePago: '',
    valorPagar: '96657.80',
    totalItbisRetencion: '',
    totalIsrRetencion: '',
    montoImpuestoAdicional: '',
    impuestosAdicionales: [],
    terminoPago: '',
    bancoPago: '',
    paginas: [],
    items: items,
    privateKey: '',
    certBase64: '');


EcfModel kE450000000011 = ecf;