
import 'package:ecf_dgii/settings.dart';
import 'package:ecf_dgii/src/models/ecf.model.dart';
import 'package:ecf_dgii/src/types/ecf.dart';
    final fechaEmision = '01-04-2020';

    List<EcfDetailsModel> items = [
      EcfDetailsModel(
          cantidad: '100.00',
          unidadMedida: '23',
          indicadorFacturacion: '1',
          indicadorBienOServ: '1',
          nombreItem: 'BLOCK',
          descripcionItem: '',
          precioUnitario: '450.0000',
          descuentoMonto: '',
          subDescuentos: [],
          impuestosAdicionales: [],
          otraMonedaDetalles: [],
          montoItem: '45000.00'),
      EcfDetailsModel(
          cantidad: '300.00',
          unidadMedida: '23',
          indicadorFacturacion: '1',
          indicadorBienOServ: '1',
          nombreItem: 'VARILLAS',
          descripcionItem: '',
          precioUnitario: '350.0000',
          descuentoMonto: '',
          subDescuentos: [],
          impuestosAdicionales: [],
          otraMonedaDetalles: [],
          montoItem: '105000.00'),
      EcfDetailsModel(
          cantidad: '200.00',
          unidadMedida: '23',
          indicadorFacturacion: '1',
          indicadorBienOServ: '1',
          nombreItem: 'CINZ',
          descripcionItem: '',
          precioUnitario: '425.0000',
          descuentoMonto: '',
          subDescuentos: [],
          impuestosAdicionales: [],
          otraMonedaDetalles: [],
          montoItem: '85000.00'),
      EcfDetailsModel(
          cantidad: '50.00',
          unidadMedida: '23',
          indicadorFacturacion: '1',
          indicadorBienOServ: '1',
          nombreItem: 'CLAVOS DE MEDIA',
          descripcionItem: '',
          precioUnitario: '550.0000',
          descuentoMonto: '',
          subDescuentos: [],
          impuestosAdicionales: [],
          otraMonedaDetalles: [],
          montoItem: '27500.00'),
      EcfDetailsModel(
          cantidad: '50.00',
          unidadMedida: '23',
          indicadorFacturacion: '1',
          indicadorBienOServ: '1',
          nombreItem: 'CLAVOS DE CUARTA',
          descripcionItem: '',
          precioUnitario: '325.0000',
          descuentoMonto: '',
          subDescuentos: [],
          impuestosAdicionales: [],
          otraMonedaDetalles: [],
          montoItem: '16250.00'),
      EcfDetailsModel(
          cantidad: '60.00',
          unidadMedida: '23',
          indicadorFacturacion: '2',
          indicadorBienOServ: '1',
          nombreItem: 'ALAMBRE DULCE',
          descripcionItem: '',
          precioUnitario: '250.0000',
          descuentoMonto: '',
          subDescuentos: [],
          impuestosAdicionales: [],
          otraMonedaDetalles: [],
          montoItem: '15000.00'),
      EcfDetailsModel(
          cantidad: '250.00',
          unidadMedida: '23',
          indicadorFacturacion: '2',
          indicadorBienOServ: '1',
          nombreItem: 'CEMENTO BLANCO',
          descripcionItem: '',
          precioUnitario: '250.0000',
          descuentoMonto: '',
          subDescuentos: [],
          impuestosAdicionales: [],
          otraMonedaDetalles: [],
          montoItem: '62500.00'),
      EcfDetailsModel(
          cantidad: '400.00',
          unidadMedida: '23',
          indicadorFacturacion: '2',
          indicadorBienOServ: '1',
          nombreItem: 'CEMENTO GRIS',
          descripcionItem: '',
          precioUnitario: '250.0000',
          descuentoMonto: '',
          subDescuentos: [],
          impuestosAdicionales: [],
          otraMonedaDetalles: [],
          montoItem: '100000.00'),
      EcfDetailsModel(
          cantidad: '30.00',
          unidadMedida: '23',
          indicadorFacturacion: '2',
          indicadorBienOServ: '1',
          nombreItem: 'COLORANTE',
          descripcionItem: '',
          precioUnitario: '250.0000',
          descuentoMonto: '',
          subDescuentos: [],
          impuestosAdicionales: [],
          otraMonedaDetalles: [],
          montoItem: '7500.00'),
      EcfDetailsModel(
          cantidad: '60.00',
          unidadMedida: '23',
          indicadorFacturacion: '2',
          indicadorBienOServ: '1',
          nombreItem: 'TINER',
          descripcionItem: '',
          precioUnitario: '250.0000',
          descuentoMonto: '',
          subDescuentos: [],
          impuestosAdicionales: [],
          otraMonedaDetalles: [],
          montoItem: '15000.00'),
    ];

    EcfModel ecf = EcfModel(
      tipoEcf: EcfType.e45,
      tempDirName: kTempDirName, // antes: 'climatic'
      indicadorMontoGravado: '0',
      numeroComprobante: 'E450000000002',
      codigoModificacion: '',
      fechaEmision: fechaEmision,
      fechaVencimiento: kfechaVencimiento, // antes: '31-12-2028'
      fechaEmisionNcfModificado: '',
      razonModificacion:
          'ANULACION DEL ENCF31 CON SECUENCIA QUE FINALIZA EN 61',
      tipoIngreso: '01',
      tipoPago: '1',
      formasDePagos: [FormaDePago('1', '560925.00')],
      sucursal: '',
      direccionEmisor: 'AVE. ISABEL AGUIAR NO. 269, ZONA INDUSTRIAL DE HERRERA',
      municipio: '010100',
      provincia: '010000',
      telefonoEmisor1: '809-472-7676',
      telefonoEmisor2: '809-491-1918',
      telefonoEmisor3: '',
      totalPaginas: '',
      rncEmisor: kRncEmisor, // antes: '130897271'
      razonSocialEmisor: 'DOCUMENTOS ELECTRONICOS DE 02',
      nombreComercial: 'DOCUMENTOS ELECTRONICOS DE 02',
      correoEmisor:
          'DOCUMENTOSELECTRONICOSDE0612345678969789+9000000000000000000000000000001@123.COM',
      website: 'www.facturaelectronica.com',
      actividadEconomica: '',
      codigoVendedor:
          'AA0000000100000000010000000002000000000300000000050000000006',
      informacionAdicionalEmisor: '',
      rncComprador: '131880681',
      razonSocialComprador: 'DOCUMENTOS ELECTRONICOS DE 03',
      nombreComprador: '',
      contactoComprador: 'MARCOS LATIPLOL',
      correoComprador: 'MARCOSLATIPLOL@KKKK.COM',
      telefonoAdicional: '',
      direccionComprador:
          'CALLE JACINTO DE LA CONCHA FELIZ ESQUINA 27 DE FEBRERO,FRENTE A DOMINO',
      municipioComprador: '010100',
      provinciaComprador: '010000',
      codigoInternoComprador: '10633440',
      fechaEntrega: '10-10-2020',
      fechaOrdenCompra: '10-11-2018',
      numeroOrdenCompra: '4500352238',
      numeroFacturaInterna: '123456789016',
      numeroPedidoInterno: '123456789016',
      numeroContenedor: '',
      numeroReferencia: '',
      zonaVenta: 'NORTE',
      rutaVenta: '',
      conductor: 'Rafael P¿rez',
      documentoTransporte: '363636',
      ficha: 'J-1234',
      placa: 'A639689',
      rutaTransporte: 'B-Sur',
      zonaTransporte: 'Interior-1',
      numeroAlbaran: '3634258',
      totalGravado: '478750.00',
      totalGravado18: '278750.00',
      totalGravado16: '200000.00',
      totalGravadoTasa0: '',
      montoExento: '',
      totalItbis: '82175.00',
      totalItbis18: '50175.00',
      totalItbis16: '32000.00',
      totalItbisTasa0: '',
      itbis1: '18',
      itbis2: '16',
      itbis3: '',
      montoTotal: '560925.00',
      montoPeriodo: '',
      montoAvancePago: '',
      valorPagar: '560925.00',
      totalItbisRetencion: '',
      totalIsrRetencion: '',
      montoImpuestoAdicional: '',
      impuestosAdicionales: [],
      terminoPago: '',
      bancoPago: '',
      paginas: [],
      items: items,
      privateKey: '',
      certBase64: '',
    );

    EcfModel kE450000000002 = ecf;
