
import 'package:ecf_dgii/settings.dart';
import 'package:ecf_dgii/src/models/ecf.model.dart';
import 'package:ecf_dgii/src/types/ecf.dart';

    final fechaEmision = '01-04-2020';

    List<EcfDetailsModel> items = [
      EcfDetailsModel(
          cantidad: '1.00',
          unidadMedida: '23',
          codigos: [TipoCodigo(tipoCodigo: 'Interno', codigoItem: '1521')],
          indicadorFacturacion: '3',
          indicadorBienOServ: '1',
          nombreItem: 'Gouda Import',
          descripcionItem: '',
          precioUnitario: '179.0000',
          descuentoMonto: '',
          subDescuentos: [],
          impuestosAdicionales: [],
          otraMonedaDetalles: [],
          montoItem: '179.00'),
      EcfDetailsModel(
          cantidad: '2.00',
          unidadMedida: '23',
          codigos: [TipoCodigo(tipoCodigo: 'Interno', codigoItem: '1521')],
          indicadorFacturacion: '3',
          indicadorBienOServ: '2',
          nombreItem: 'Gouda Impor Lonja',
          descripcionItem: '',
          precioUnitario: '179.0000',
          descuentoMonto: '',
          subDescuentos: [],
          impuestosAdicionales: [],
          otraMonedaDetalles: [],
          montoItem: '358.00'),
      EcfDetailsModel(
          cantidad: '1.00',
          unidadMedida: '43',
          codigos: [TipoCodigo(tipoCodigo: 'Interno', codigoItem: '1521')],
          indicadorFacturacion: '3',
          indicadorBienOServ: '2',
          nombreItem: 'Bon Helado',
          descripcionItem: '',
          precioUnitario: '239.0000',
          descuentoMonto: '',
          subDescuentos: [],
          impuestosAdicionales: [],
          otraMonedaDetalles: [],
          montoItem: '239.00'),
      EcfDetailsModel(
          cantidad: '2.00',
          unidadMedida: '43',
          codigos: [TipoCodigo(tipoCodigo: 'Interno', codigoItem: '1521')],
          indicadorFacturacion: '3',
          indicadorBienOServ: '2',
          nombreItem: 'Butterball pavo',
          descripcionItem: '',
          precioUnitario: '155.0000',
          descuentoMonto: '',
          subDescuentos: [],
          impuestosAdicionales: [],
          otraMonedaDetalles: [],
          montoItem: '310.00'),
    ];

    EcfModel ecf = EcfModel(
      tipoEcf: EcfType.e46,
      tempDirName: kTempDirName, // antes: 'arenal'
      indicadorMontoGravado: '',
      numeroComprobante: 'E460000000011',
      codigoModificacion: '',
      fechaEmision: fechaEmision,
      fechaVencimiento: kfechaVencimiento, // antes: '31-12-2028'
      fechaEmisionNcfModificado: '',
      razonModificacion: '',
      tipoIngreso: '01',
      tipoPago: '1',
      formasDePagos: [FormaDePago('1', '1086.00')],
      sucursal: '',
      direccionEmisor: 'AVE. ISABEL AGUIAR NO. 269, ZONA INDUSTRIAL DE HERRERA',
      municipio: '010100',
      provincia: '010000',
      telefonoEmisor1: '809-472-7676',
      telefonoEmisor2: '809-491-1918',
      telefonoEmisor3: '',
      totalPaginas: '',
      rncEmisor: kRncEmisor, // antes: '123006624'
      razonSocialEmisor: 'DOCUMENTOS ELECTRONICOS DE 02',
      nombreComercial: 'DOCUMENTOS ELECTRONICOS DE 02',
      correoEmisor:
          'DOCUMENTOSELECTRONICOSDE0612345678969789+9000000000000000000000000000001@123.COM',
      website: 'www.facturaelectronica.com',
      actividadEconomica: '',
      codigoVendedor:
          'AA0000000100000000010000000002000000000300000000050000000006',
      informacionAdicionalEmisor: '',
      rncComprador: '',
      razonSocialComprador: 'DOCUMENTOS ELECTRONICOS DE 03',
      nombreComprador: '',
      contactoComprador: 'MARCOS LATIPLOL',
      correoComprador: 'MARCOSLATIPLOL@KKKK.COM',
      telefonoAdicional: '',
      direccionComprador:
          'CALLE JACINTO DE LA CONCHA FELIZ ESQUINA 27 DE FEBRERO,FRENTE A DOMINO',
      municipioComprador: '',
      provinciaComprador: '',
      codigoInternoComprador: '',
      fechaEntrega: '',
      fechaOrdenCompra: '',
      numeroOrdenCompra: '',
      numeroFacturaInterna: '123456789016',
      numeroPedidoInterno: '123456789016',
      zonaVenta: 'NORTE',
      rutaVenta: '',
      identificadorExtranjero: '350555123',
      conductor: '',
      documentoTransporte: '',
      ficha: '',
      placa: '',
      rutaTransporte: '',
      zonaTransporte: '',
      numeroAlbaran: '',
      totalGravado: '1086.00',
      totalGravado18: '',
      totalGravado16: '',
      totalGravadoTasa0: '1086.00',
      montoExento: '',
      totalItbis: '0.00',
      totalItbis18: '',
      totalItbis16: '',
      totalItbisTasa0: '0.00',
      itbis1: '',
      itbis2: '',
      itbis3: '0',
      montoTotal: '1086.00',
      montoPeriodo: '1086.00',
      montoAvancePago: '',
      valorPagar: '1086.00',
      tipoMoneda: '',
      tipoCambio: '',
      montoGravadoTotalOtraMoneda: '',
      montoGravadoTotalOtraMoneda1: '',
      montoGravadoTotalOtraMoneda2: '',
      montoGravadoTotalOtraMoneda3: '',
      totalItbisOtraMoneda: '',
      totalItbis1OtraMoneda: '',
      totalItbis2OtraMoneda: '',
      totalItbis3OtraMoneda: '',
      montoExentoOtraMoneda: '',
      montoTotalOtraMoneda: '',
      totalItbisRetencion: '',
      totalIsrRetencion: '',
      montoImpuestoAdicional: '',
      impuestosAdicionales: [],
      terminoPago: '',
      bancoPago: '',
      paginas: [],
      items: items,
      privateKey: '',
      certBase64: '',
    );

    EcfModel kE460000000011 = ecf;

    