
import 'package:ecf_dgii/settings.dart';
import 'package:ecf_dgii/src/models/ecf.model.dart';
import 'package:ecf_dgii/src/types/ecf.dart';
    final fechaEmision = '01-04-2020';

    List<EcfDetailsModel> items = [
      EcfDetailsModel(
          cantidad: '100.00',
          unidadMedida: '43',
          codigos: [TipoCodigo(tipoCodigo: 'INTERNA', codigoItem: '123456')],
          indicadorFacturacion: '3',
          indicadorBienOServ: '1',
          nombreItem: 'AGUACATE CRIOLLO',
          descripcionItem: '',
          precioUnitario: '18000.00',
          descuentoMonto: '',
          subDescuentos: [],
          impuestosAdicionales: [],
          otraMonedaDetalles: [],
          montoItem: '1800000.00'),
    ];

    EcfModel ecf = EcfModel(
        tipoEcf: EcfType.e46,
        tempDirName: kTempDirName,
        indicadorMontoGravado: '',
        numeroComprobante: 'E460000000001',
        codigoModificacion: '',
        fechaEmision: fechaEmision,
        fechaVencimiento: kfechaVencimiento,
        fechaEmisionNcfModificado: '',
        razonModificacion:
            'ANULACION DEL ENCF31 CON SECUENCIA QUE FINALIZA EN 61',
        tipoIngreso: '01',
        tipoPago: '2',
        terminoPago: '1 mes',
        fechaLimitePago: '06-05-2020',
        formasDePagos: [FormaDePago('2', '1800000.00')],
        sucursal: '',
        direccionEmisor:
            'AVE. ISABEL AGUIAR NO. 269, ZONA INDUSTRIAL DE HERRERA',
        municipio: '010101',
        provincia: '010000',
        telefonoEmisor1: '809-472-7676',
        telefonoEmisor2: '809-491-1918',
        telefonoEmisor3: '',
        totalPaginas: '',
        rncEmisor: kRncEmisor,
        razonSocialEmisor: 'DOCUMENTOS ELECTRONICOS DE 02',
        nombreComercial: 'DOCUMENTOS ELECTRONICOS DE 02',
        correoEmisor:
            'DOCUMENTOSELECTRONICOSDE0612345678969789+9000000000000000000000000000001@123.COM',
        website: 'www.facturaelectronica.com',
        actividadEconomica: '',
        codigoVendedor:
            'AA0000000100000000010000000002000000000300000000050000000006',
        informacionAdicionalEmisor: '',
        rncComprador: '131880681',
        razonSocialComprador: 'ZONA FRANCA LOI',
        nombreComprador: '',
        contactoComprador: 'MARCOS LLUBERES',
        correoComprador: 'MARCOSLLUBERES@KKKK.COM',
        direccionComprador: 'ZONA HAINA',
        municipioComprador: '010100',
        provinciaComprador: '010000',
        codigoInternoComprador: '10633441',
        fechaEmbarque: '10-04-2020',
        numeroEmbarque: '10010-1207-000254',
        numeroContenedor: 'ERTY227958722',
        numeroReferencia: '1448',
        nombrePuertoEmbarque: 'ZONA HAINA',
        condicionesEntrega: 'FOB',
        totalFob: '1800.00',
        seguro: '250.00',
        flete: '22.00',
        totalCif: '2000.00',
        regimenAduanero: 'EXPORTACION NACIONAL',
        nombrePuertoSalida: 'DOSDQ',
        nombrePuertoDesembarque: 'PTO RICO',
        pesoBruto: '25000.00',
        pesoNeto: '24878.00',
        unidadPesoBruto: '21',
        unidadPesoNeto: '21',
        cantidadBulto: '250.00',
        unidadBulto: '25',
        volumenBulto: '45',
        unidadVolumen: '27',
        viaTransporte: '02',
        paisOrigen: 'REPUBLICA DOMINICANA',
        direccionDestino: 'CALLE GUALLUBI NO. 09',
        paisDestino: 'PUERTO RICO',
        fechaEntrega: '07-04-2020',
        contactoEntrega: 'JACINTO MANON',
        direccionEntrega: 'ZONA HAINA',
        telefonoAdicional: '809-555-5050',
        fechaOrdenCompra: '10-03-2020',
        numeroOrdenCompra: '4500352230',
        numeroFacturaInterna: '123456789016',
        numeroPedidoInterno: '123456789016',
        zonaVenta: '',
        rutaVenta: '',
        conductor: '',
        documentoTransporte: '',
        ficha: '',
        placa: '',
        rutaTransporte: '',
        zonaTransporte: '',
        numeroAlbaran: '56789UJILLL',
        totalGravado: '1800000.00',
        totalGravado18: '',
        totalGravado16: '',
        totalGravadoTasa0: '1800000.00',
        montoExento: '',
        totalItbis: '0.00',
        totalItbis18: '',
        totalItbis16: '',
        totalItbisTasa0: '0.00',
        itbis1: '',
        itbis2: '',
        itbis3: '0',
        montoTotal: '1800000.00',
        montoPeriodo: '',
        montoAvancePago: '',
        valorPagar: '',
        tipoMoneda: '',
        tipoCambio: '',
        montoGravadoTotalOtraMoneda: '',
        montoGravadoTotalOtraMoneda1: '',
        montoGravadoTotalOtraMoneda2: '',
        montoGravadoTotalOtraMoneda3: '',
        totalItbisOtraMoneda: '',
        totalItbis1OtraMoneda: '',
        totalItbis2OtraMoneda: '',
        totalItbis3OtraMoneda: '',
        montoExentoOtraMoneda: '',
        montoTotalOtraMoneda: '',
        totalItbisRetencion: '',
        totalIsrRetencion: '',
        montoImpuestoAdicional: '',
        impuestosAdicionales: [],
        bancoPago: '',
        paginas: [],
        items: items,
        privateKey: '',
        certBase64: '');
    
    EcfModel kE460000000001 = ecf;

    