
import 'package:ecf_dgii/settings.dart';
import 'package:ecf_dgii/src/models/ecf.model.dart';
import 'package:ecf_dgii/src/types/ecf.dart';

    final fechaEmision = '01-04-2020';

    List<EcfDetailsModel> items = [
      EcfDetailsModel(
          cantidad: '24.00',
          unidadMedida: '19',
          indicadorFacturacion: '4',
          indicadorBienOServ: '2',
          nombreItem: 'Asesoria Legal P/H',
          descripcionItem: '',
          precioUnitario: '1500.0000',
          descuentoMonto: '',
          subDescuentos: [],
          impuestosAdicionales: [],
          retencion: Retencion(
              indicadorAgenteRetencionoPercepcion: '1',
              montoITBISRetenido: '',
              montoISRRetenido: '9720.00'),
          otraMonedaDetalles: [
          
          ],
          montoItem: '36000.00'),
      EcfDetailsModel(
          cantidad: '48.00',
          unidadMedida: '19',
          indicadorFacturacion: '4',
          indicadorBienOServ: '2',
          nombreItem: 'Asesoria Legal P/H',
          descripcionItem: '',
          precioUnitario: '2500.0000',
          descuentoMonto: '',
          subDescuentos: [],
          impuestosAdicionales: [],
          retencion: Retencion(
              indicadorAgenteRetencionoPercepcion: '1',
              montoITBISRetenido: '',
              montoISRRetenido: '32400.00'),
          otraMonedaDetalles: [
         
          ],
          montoItem: '120000.00'),
      EcfDetailsModel(
          cantidad: '64.00',
          unidadMedida: '19',
          indicadorFacturacion: '4',
          indicadorBienOServ: '2',
          nombreItem: 'Asesoria Legal P/H',
          descripcionItem: '',
          precioUnitario: '3000.0000',
          descuentoMonto: '',
          subDescuentos: [],
          impuestosAdicionales: [],
          retencion: Retencion(
              indicadorAgenteRetencionoPercepcion: '1',
              montoITBISRetenido: '',
              montoISRRetenido: '51840.00'),
          otraMonedaDetalles: [
          
          ],
          montoItem: '192000.00'),
    ];

    EcfModel ecf = EcfModel(
        tipoEcf: EcfType.e47,
        tempDirName: kTempDirName,
        indicadorMontoGravado: '',
        numeroComprobante: 'E470000000010',
        codigoModificacion: '',
        fechaEmision: fechaEmision,
        fechaVencimiento: kfechaVencimiento,
        fechaEmisionNcfModificado: '',
        razonModificacion:
            'ANULACION DEL ENCF31 CON SECUENCIA QUE FINALIZA EN 61',
        tipoIngreso: '',
        tipoPago: '1',
        terminoPago: '',
        formasDePagos: [FormaDePago('1', '347100.00')],
        sucursal: '',
        direccionEmisor:
            'AVE. ISABEL AGUIAR NO. 269, ZONA INDUSTRIAL DE HERRERA',
        municipio: '010100',
        provincia: '010000',
        telefonoEmisor1: '809-472-7676',
        telefonoEmisor2: '809-491-1918',
        telefonoEmisor3: '',
        totalPaginas: '',
        rncEmisor: kRncEmisor,
        razonSocialEmisor: 'DOCUMENTOS ELECTRONICOS DE 02',
        nombreComercial: 'DOCUMENTOS ELECTRONICOS DE 02',
        correoEmisor:
            'DOCUMENTOSELECTRONICOSDE0612345678969789+9000000000000000000000000000001@123.COM',
        website: 'www.facturaelectronica.com',
        actividadEconomica: '',
        codigoVendedor: '',
        informacionAdicionalEmisor: '',
        rncComprador: '',
        identificadorExtranjero: '350555123',
        razonSocialComprador: 'DOCUMENTOS ELECTRONICOS DE 03',
        nombreComprador: '',
        contactoComprador: '',
        correoComprador: '',
        telefonoAdicional: '',
        direccionComprador: '',
        municipioComprador: '',
        provinciaComprador: '',
        codigoInternoComprador: '',
        fechaEntrega: '',
        fechaOrdenCompra: '',
        numeroOrdenCompra: '',
        numeroFacturaInterna: '123456789016',
        numeroPedidoInterno: '123456789016',
        zonaVenta: '',
        rutaVenta: '',
        paisDestino: '',
        conductor: '',
        documentoTransporte: '',
        ficha: '',
        placa: '',
        rutaTransporte: '',
        zonaTransporte: '',
        numeroAlbaran: '',
        totalGravado: '',
        totalGravado18: '',
        totalGravado16: '',
        totalGravadoTasa0: '',
        montoExento: '348000.00',
        totalItbis: '',
        totalItbis18: '',
        totalItbis16: '',
        totalItbisTasa0: '',
        itbis1: '',
        itbis2: '',
        itbis3: '',
        montoTotal: '348000.00',
        montoPeriodo: '348000.00',
        montoAvancePago: '',
        valorPagar: '348000.00',
        tipoMoneda: '',
        tipoCambio: '',
        montoGravadoTotalOtraMoneda: '',
        montoGravadoTotalOtraMoneda1: '',
        montoGravadoTotalOtraMoneda2: '',
        montoGravadoTotalOtraMoneda3: '',
        totalItbisOtraMoneda: '',
        totalItbis1OtraMoneda: '',
        totalItbis2OtraMoneda: '',
        totalItbis3OtraMoneda: '',
        montoExentoOtraMoneda: '',
        montoTotalOtraMoneda: '',
        totalItbisRetencion: '',
        totalIsrRetencion: '93960.00',
        montoImpuestoAdicional: '',
        impuestosAdicionales: [],
        bancoPago: '',
        paginas: [],
        items: items,
        privateKey: '',
        certBase64: '');

    EcfModel kE470000000010 = ecf;

