import 'package:ecf_dgii/settings.dart';
import 'package:ecf_dgii/src/models/ecf.model.dart';
import 'package:ecf_dgii/src/types/ecf.dart';

final fechaEmision = '01-04-2020';

List<EcfDetailsModel> items = [
  EcfDetailsModel(
      cantidad: '1.00',
      unidadMedida: '43',
      codigos: [],
      indicadorFacturacion: '4',
      indicadorBienOServ: '2',
      nombreItem: 'LICENCIA WYI',
      descripcionItem: '',
      precioUnitario: '180000.00',
      descuentoMonto: '',
      subDescuentos: [],
      impuestosAdicionales: [],
      retencion: Retencion(
          indicadorAgenteRetencionoPercepcion: '1',
          montoITBISRetenido: '',
          montoISRRetenido: '48600.00'),
      otraMonedaDetalles: [
        OtraMonedaDetalle(
            precioOtraMoneda: '3000.0000',
            descuentoOtraMoneda: '',
            recargoOtraMoneda: '',
            montoItemOtraMoneda: '3000.00')
      ],
      montoItem: '180000.00'),
];

EcfModel ecf = EcfModel(
    tipoEcf: EcfType.e47,
    tempDirName: kTempDirName,
    indicadorMontoGravado: '',
    numeroComprobante: 'E470000000001',
    codigoModificacion: '',
    fechaEmision: fechaEmision,
    fechaVencimiento: kfechaVencimiento,
    fechaEmisionNcfModificado: '',
    razonModificacion: '',
    tipoIngreso: '',
    tipoPago: '',
    formasDePagos: [],
    sucursal: '',
    direccionEmisor: 'AVE. ISABEL AGUIAR NO. 269, ZONA INDUSTRIAL DE HERRERA',
    municipio: '010101',
    provincia: '010000',
    telefonoEmisor1: '809-472-7676',
    telefonoEmisor2: '809-491-1918',
    telefonoEmisor3: '',
    totalPaginas: '',
    rncEmisor: kRncEmisor,
    razonSocialEmisor: 'DOCUMENTOS ELECTRONICOS DE 02',
    nombreComercial: 'DOCUMENTOS ELECTRONICOS DE 02',
    correoEmisor:
        'DOCUMENTOSELECTRONICOSDE0612345678969789+9000000000000000000000000000001@123.COM',
    website: 'www.facturaelectronica.com',
    actividadEconomica: '',
    codigoVendedor: '',
    informacionAdicionalEmisor: '',
    rncComprador: '',
    identificadorExtranjero: '533445888',
    razonSocialComprador: 'ALEJA FERMIN SANTOS',
    nombreComprador: '',
    contactoComprador: '',
    correoComprador: '',
    telefonoAdicional: '',
    direccionComprador: '',
    municipioComprador: '',
    provinciaComprador: '',
    codigoInternoComprador: '',
    fechaEntrega: '',
    fechaOrdenCompra: '',
    numeroOrdenCompra: '',
    numeroFacturaInterna: '123456789016',
    numeroPedidoInterno: '123456789016',
    zonaVenta: '',
    rutaVenta: '',
    paisDestino: '',
    conductor: '',
    documentoTransporte: '',
    ficha: '',
    placa: '',
    rutaTransporte: '',
    zonaTransporte: '',
    numeroAlbaran: '',
    totalGravado: '',
    totalGravado18: '',
    totalGravado16: '',
    totalGravadoTasa0: '',
    montoExento: '180000.00',
    totalItbis: '',
    totalItbis18: '',
    totalItbis16: '',
    totalItbisTasa0: '',
    itbis1: '',
    itbis2: '',
    itbis3: '',
    montoTotal: '180000.00',
    montoPeriodo: '',
    montoAvancePago: '',
    valorPagar: '',
    tipoMoneda: 'USD',
    tipoCambio: '60.0000',
    montoGravadoTotalOtraMoneda: '',
    montoGravadoTotalOtraMoneda1: '',
    montoGravadoTotalOtraMoneda2: '',
    montoGravadoTotalOtraMoneda3: '',
    totalItbisOtraMoneda: '',
    totalItbis1OtraMoneda: '',
    totalItbis2OtraMoneda: '',
    totalItbis3OtraMoneda: '',
    montoExentoOtraMoneda: '3000.00',
    montoTotalOtraMoneda: '3000.00',
    totalItbisRetencion: '',
    totalIsrRetencion: '48600.00',
    montoImpuestoAdicional: '',
    impuestosAdicionales: [],
    terminoPago: '',
    bancoPago:
        'BB0111111111111111111111111111111111111111111111111111111111111111111111111',
    tipoCuentaPago: '',
    numeroCuentaPago: 'BB00058745214789635111111111',
    paginas: [],
    items: items,
    privateKey: '',
    certBase64: '');

EcfModel kE470000000001 = ecf;